name: whatever action

on:
  push:
    paths:
      - 'cacamole'
    branches:
      - main

jobs:
   helloSara:
    runs-on: ubuntu-latest
    steps:
      - name: demo for Sara
        run: echo 'Hello Sara'
   helloMen:
    runs-on: windows-latest
    needs: helloSara
    steps:
      - name: francesco
        run: "hello francesco"
      - name: bobby
        run: "hello bobby"
